# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "496e91cd7345661810022096ef236a65"
name = "Ordery"
application_url = "https://inch-refinance-jackson-disturbed.trycloudflare.com"
embedded = true
handle = "ordery-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = ["orders/create", "orders/updated"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = ["https://inch-refinance-jackson-disturbed.trycloudflare.com/auth/callback", "https://inch-refinance-jackson-disturbed.trycloudflare.com/auth/shopify/callback", "https://inch-refinance-jackson-disturbed.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
