# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "496e91cd7345661810022096ef236a65"
name = "Ordery"
application_url = "https://ordery-app.vercel.app/app"
embedded = true
handle = "ordery-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = ["orders/create", "orders/updated"]
  uri = "https://ordery-app.vercel.app/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://ordery-app.vercel.app/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://ordery-app.vercel.app/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  # All compliance topics can hit one endpoint
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "https://ordery-app.vercel.app/compliance-webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products,read_all_orders,write_orders,write_draft_orders"

[auth]
redirect_urls = ["https://ordery-app.vercel.app/auth/callback", "https://ordery-app.vercel.app/auth/shopify/callback", "https://ordery-app.vercel.app/api/auth/callback"]

[pos]
embedded = false
